
CREATE TABLE CHECK_OUT (
    BOOK_ID NUMBER NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    STATE VARCHAR2(20) NOT NULL,
    CHECK_OUT_DATE DATE NOT NULL,
    CHECK_IN_DATE DATE NOT NULL
);

ALTER TABLE CHECK_OUT ADD CONSTRAINT PK PRIMARY KEY(BOOK_ID);
ALTER TABLE CHECK_OUT ADD CONSTRAINT FK1 
FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID);

/*
CREATE TRIGGER STATE_RESERVED_TRIGGER
AFTER INSERT ON CHECK_OUT
FOR EACH ROW
BEGIN
    UPDATE BOOK
    SET BOOK.STATE = :NEW.STATE
    WHERE BOOK.BOOK_ID = :NEW.BOOK_ID;
END;
COMMIT;
*/
